### PR TITLE
Pull Request for the NBT placeholder replacer

### PR DESCRIPTION
**Pull request by JimiIT92**
feat(NBTUtils): replace placeholders inside NBT Tags

- Can take an ITextComponent as input or a String
- Gives a new ITextComponent or a String with the replaced placeholders
- Changed the Summon action words count check, to allow to summon mobs with display name a phrase

Might break Drop and Summon actions, i did some tests and it seems not

### CODE REVIEW

**Comment by JimiIT92** [comment]
Implemented the NBT replacer to Summon action too. Meta actions worked automatically since they already recall the parse function of the actions :)

**Comment by iGoodie** [comment]
I might've changed my mind on reparsing action on each event occurrence.
You are right with the meta-actions calling the contained actions' handlers!
I'll consider merging this PR after a brief testing 🎉 @JimiIT92

**Comment by iGoodie** [comment]
With your insights @JimiIT92, I realized that we need to implement a distinct placeholder evaluation logic for each action for safety purposes. 🥇 

E.g we couldn't let user have something like:
```coffeescript
BOTH
 DROP apple
 ${actor}
 DROP stick
 ON ...
```
Where a delimiter (`AND`) is replaced by a placeholder.

I'm starting to implement this to each non-meta action starting from 626b491

Thanks for you insights, credits will be given to you on the next release! @JimiIT92 🎉

**Comment by JimiIT92** [comment]
I tried to implement the logic to replace the Item Lore NBT but had no success. Also can't think about other nbts needed :/

**Pull request closed without merging**
